name: image-api-svc build and push

on:
  push:
    paths:
      - 'image-svc/**'
      - '.github/workflows/build-push-image-api-svc.yaml'
    branches:
      - 'main'

jobs:
  docker:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      #log current directory
      - name: Log current directory
        run: pwd
      -
        name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: image-svc/Dockerfile
          tags: gmmeng/image-api-svc:latest
          platforms: linux/amd64, linux/x86_64
      -
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/gmmeng/random-words-svc:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
  
      - 
        name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'