name: word-svc build and push
on:
  push:
    paths:
      - 'random-words-svc/**'
      - '.github/workflows/build-push-word-svc.yaml'
    branches:
      - 'main'

jobs:
  docker:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: gmmeng/random-words-svc:latest
          platforms: linux/amd64, linux/x86_64
          file: random-words-svc/Dockerfile
    outputs:
      digest: ${{ steps.build_and_push.outputs.digest}}
      
  sbom-sender:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Send SBOM to ServiceNow API
        uses: gmmoreiracan/servicenow-sbom-sender@main
        with:
          imagePath: gmmeng/random-words-svc:latest
          imageDigest: ${{ needs.docker.outputs.digest }}